[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pybin"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "wheel"
]

[dependency-groups]
dev = [
    "twine>3",
    "pytest",
    "hypothesis"
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
