name: traefik
upstream_repo: https://github.com/traefik/traefik
version: "3.6.7"
pypi_version: "3.6.7"
license: MIT

url_template: "{repo}/releases/download/v{version}/{name}_v{version}_{target}.tar.gz"

targets:
  darwin_arm64: macos_arm
  darwin_amd64: macos_x86
  linux_arm64: linux_arm
  linux_amd64: linux_x86
